spring:
  application:
    name: jpalab
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/internship_management_system
    username: postgres
    password: omarqwer1
    driverClassName: org.postgresql.Driver